name: qgroundcontrol
version: '3.2+git'
summary: Cross-platform ground control station for drones 
description: |
  QGroundControl provides full flight control and configuration for ArduPilot or PX4 Pro powered vehicles. The goal for QGroundControl is improved ease of use for new users as well as high end feature support for experienced users. 


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  qgroundcontrol:
    plugin: dump
    source: https://github.com/mavlink/qgroundcontrol/releases/download/v3.3.2/QGroundControl.tar.bz2

apps:
  start:
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/pulseradio:$SNAP/Qt/libs:$LD_LIBRARY_PATH
      QML2_IMPORT_PATH: $SNAP/Qt/qml
      QT_PLUGIN_PATH: $SNAP/Qt/plugins
    command: QGroundControl
    desktop: qgroundcontrol.desktop
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - network-bind
      - network-manager
      - pulseaudio
      - removable-media
      - unity7
      - opengl