
name: qgroundcontrol
version: '3.2+git'
summary: Cross-platform ground control station for drones 
description: |
  QGroundControl provides full flight control and configuration for ArduPilot or PX4 Pro powered vehicles. The goal for QGroundControl is improved ease of use for new users as well as high end feature support for experienced users. 


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  qgroundcontrol:
    plugin: dump
    source: https://github.com/mavlink/qgroundcontrol/releases/download/v3.3.2/QGroundControl.tar.bz2

apps:
  start:
    command: ./qgroundcontrol-start.sh