name: qgroundcontrol
version: '3.2+git'
summary: Cross-platform ground control station for drones 
description: |
  QGroundControl provides full flight control and configuration for ArduPilot or PX4 Pro powered vehicles. The goal for QGroundControl is improved ease of use for new users as well as high end feature support for experienced users. 


grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  qgroundcontrol:
    plugin: autotools
    source: https://github.com/mavlink/qgroundcontrol.git
    after: [qt]
  qt:
    plugin: qtbuilder
    qt-version: 5.9.3
    qt-source-git: https://code.qt.io/qt/qt5.git
    qt-submodules: ['qtbase', 'qtimageformats']
    # qt-patches-base-url: https://raw.githubusercontent.com/telegramdesktop/tdesktop/master/Telegram/Patches
    # qt-patches-path: patches
    # qt-extra-plugins:
    #   - platforminputcontexts:
    #     - https://github.com/telegramdesktop/fcitx.git
    #     - https://github.com/telegramdesktop/hime.git
    environment:
      - CC: gcc-7
      - CXX: g++-7
      - QMAKE_CC: gcc-7
      - QMAKE_CXX: g++-7
    build-packages:
      - libasound2-dev
      - libdbusmenu-glib-dev
      - libffi-dev
      - liblzma-dev
      - libpulse-dev
      - libssl-dev
      - libx11-xcb-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-sync-dev
      - libxcb-util0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libxrender-dev
    configflags:
      - -prefix
      - $SNAPCRAFT_STAGE
      - -release
      - -force-debug-info
      - -opensource
      - -confirm-license
      - -qt-zlib
      - -qt-libpng
      - -qt-libjpeg
      - -qt-freetype
      - -qt-harfbuzz
      - -qt-pcre
      - -qt-xcb
      - -qt-xkbcommon-x11
      - -static
      - -dbus-runtime
      - -openssl-linked
      - -nomake
      - examples
      - -nomake
      - tests
    after:
      - libxkbcommon
      - gcc7
    prime: [-./*]

  libxkbcommon:
    source: https://github.com/xkbcommon/libxkbcommon.git
    source-depth: 1
    plugin: autotools
    build-packages:
      - xutils-dev
      - bison
      - python-xcbgen
    configflags:
      - --disable-x11
    prime: [-./*]

  gcc7:
    plugin: nil
    build-packages:
      - libmpc-dev
      - libcloog-ppl-dev
    prepare: |
      echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" | \
            sudo tee /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 60C317803A41BA51845E371A1E9377A2BA9EF27F
      sudo apt-get update \
        -o Dir::Etc::sourcelist="sources.list.d/ubuntu-toolchain-r.list" \
        -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
    install: |
      sudo apt install gcc-7 g++-7 -o Debug::pkgProblemResolver=yes --no-install-recommends -y
      sudo apt-mark auto gcc-7 g++-7
      sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r.list
    prime: [-./*]

apps: 
  start: 
    environment: 
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/pulseradio:$SNAP/Qt/libs:$LD_LIBRARY_PATH 
      QML2_IMPORT_PATH: $SNAP/Qt/qml 
      QT_PLUGIN_PATH: $SNAP/Qt/plugins 
    command: QGroundControl 
    desktop: qgroundcontrol.desktop 
    plugs: 
      - desktop 
      - desktop-legacy 
      - gsettings 
      - home 
      - network 
      - network-bind 
      - network-manager 
      - pulseaudio 
      - removable-media 
      - unity7 
      - opengl